name: Demo Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'


jobs:
  Test-Google-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: echo "Hello World"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Build and run tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure

  
  

